spring:
  application:
    name: blogSummer

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: donghoong
    password: birdbird1!

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always
      encoding: UTF-8
